:-  consult([
        "or_story.plt",
        "simple_story.plt",
        "warsaw_standoff_story.plt",
        "semi_complex_test.plt",
        "simple_concurrent.plt",
        "user_input_parsing.plt",
        "concurrent_test.plt",
        "tas_tests.plt",
        "tas_with_wait.plt",
        "tas_true_false.plt",
        "mns.plt",
        "true_false.plt",
		"tas_with_idle.plt",
		"tas_with_idle_2.plt",
		"tas_without_idle.plt",
		"evacuation.plt"
        ]),
    run_tests.
